language: cpp
sudo: required
dist: trusty
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-8;
      export CXX=g++-8;
    fi
  - cmake --version
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .
